### ISSUE TITLE
ReEvaluationDialog -> 'Dark'. Improve the option for multiple dark spectra

### ISSUE THREAD

**Issue by mattias42** [NOVACProject/MobileDOAS#10]
Currently the option for deciding which spectra are 'dark' are somewhat magic and depending on the type of the spectrometer used. Make it possible for the user to specify the conditions for when a spectrum is dark (parameters in the configuration and then calculate intensities to determine if spectrum is dark or not).

**Comment by dnorgaard-usgs** [comment]
Possibly remove all options just like in NOVAC Program: https://github.com/NOVACProject/NOVACProgram/issues/15.  Again, confirm with Christoph first on this.

**Comment by dnorgaard-usgs** [comment]
Christoph uses default option and is ok with removing this tab.

**Comment by dnorgaard-usgs** [comment]
done
