### ISSUE TITLE
Maximum exposure time in 'adaptive' mode is too long

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#100]
When making measurement in the 'adaptive' exposure time mode, we sometimes get very long exposures. This can e.g. happen when passing under a tree. Then, the instrument decides it's very dark and selects a very long exposure time. In a separate issue, I have described what I think is a better method for determining the new exposure time. Here, I address the limit for maximum possible exposure time, regardless of how the exposure time is determined.

The user sets the integration time of the measurement in the configuration. We typically use 1000 ms. This means that the spectrometer records as many spectra as it can in 1 second, adds them up and sends them to the computer. 

However, if the light level drops (e.g. due to a tree), the new exposure time can sometimes exceed the integration time. I think that I have seen exposure times of 4 seconds or longer. Such a long exposure time is annoying, because it usually leads to oversaturated spectra and also blocks the acquisition of useful data for quite a while. I therefore suggest that the maximum permissible exposure time should be equal to the user-defined integration time. In our example, the maximum exposure time should be 1000 ms. That way the spectrometer will take 1 spectrum at 1000 ms, then re-asses the light situation, and we can stay on our acquisition rate of 1 acquisition per second.

**Comment by mattias42** [comment]
Added a fix to limit the maximum exposure time to the time-resolution of the measurement in commit 1384473ff5fbfc81ad8331cc7e13eb7264d60d26 .

**Comment by mattias42** [comment]
bug-fixed
