### ISSUE TITLE
Supporting the Ocean Optics QE65000

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#101]
We sometimes use an Ocean Optics QE65000 spectrometer for measurements when we are looking to get the best possible signal to noise ration. The QE65000 spectrometer has a back-thinned CCD detector and therefore has a much better UV sensitivity than the USB2000+ or SD2000 spectrometers have. These back-thinned detectors need to be cooled to a low temperature to reduce the spectrum noise. The QE65000 has an internal peltier cooler for this purpose.

It would be great if MobileDOAS would support this spectrometer. It would require 2 things: 
1) A field in the spectrometer configuration where the user can indicate a set point for the CCD temperature
2) An indicator of the current CCD temperature somewhere on the acquisition page so that the user can make sure the temperature is indeed at the correct set point. Ideally, this indicator would turn red or give some other warning if the temperature if more than 2 degrees off of the set point.

Ideally, the CCD temperature would also be written to the recorded STD files by simply adding a DetectorTemperature = x entry to the metadata at the bottom of the file.

I'm not exactly sure if the setDetectorTemperature command needs to be repeated between each acquisition or if it only has to happen once at the beginning. This would have to be tested. But getDetectorTemperature would need to be called after each scan in order for the current temperature to be written to the STD file.

**Comment by dnorgaard-usgs** [comment]
Needs a bit more testing but items 1 and 2 are there.  Before writing to STD files though, need to work on #71 first to make the way STD file is written cleaner.
