### ISSUE TITLE
ReEvaluate traverse - fast computer will crash the program

### ISSUE THREAD

**Issue by mattias42** [NOVACProject/MobileDOAS#13]
When running a reevaluation on a fast, modern, computer then the program will crash due to an overflow of spectra to display.

**Comment by dnorgaard-usgs** [comment]
See also https://github.com/NOVACProject/NOVACProgram/issues/19

**Comment by dnorgaard-usgs** [comment]
It does not seem like this is a problem much in MobileDOAS, if at all.  I have not been able to reproduce this problem like I was able to in the NOVACProgram (see https://github.com/NOVACProject/NOVACProgram/issues/19).  The work around, barring a better fix, is to sleep between scan evaluations.  In ReEvaluator.cpp, add following else statement to the if(pause) statement:

				if(m_pause){
					CWinThread *thread = AfxGetThread();
					m_sleeping = true;
					if(pView != 0)
						pView->PostMessage(WM_GOTO_SLEEP);
					thread->SuspendThread();
					m_sleeping = false;
				}else{
				       Sleep(200);
			        }

It is possible that if this problem occurs in MobileDOAS, that it does not need as long of a sleep time to address the issue.  It will need some experimenting.

**Comment by dnorgaard-usgs** [comment]
It appears the issue with re-evaluation in MobileDOAS was something else.  Closing the ticket, but we will reopen if needed.
