### ISSUE TITLE
EvaluationLogs with more than 4096 spectra can not be evaluated for flux

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#132]
If a mobile DOAS measurement goes on for more than 4,096 measurements, then the resulting evaluationlog cannot be loaded into the Calculate Flux from File dialog. This is annoying, as we often have more than 4,000 spectra particularly when we hand the instrument off to someone for opportunistic measurements or when we use the instrument on airborne measurements. Our last collection from Ulawun has about 30,000 measurements. The instrument ran in the car all day (highlighting the amazing stability of the software during acquisition!)  Is this an old memory limitation? Wouldn't it be easy to allow more than 4096 measurements?

**Comment by christophkern** [comment]
Attaching a sample evaluationlog with more than 4096 measurements in it.

[run13_20190703_2013evaluationLog_SO2.txt](https://github.com/NOVACProject/MobileDOAS/files/3366658/run13_20190703_2013evaluationLog_SO2.txt)

**Comment by dnorgaard-usgs** [comment]
I was able to increase "MAX_TRAVERSELENGTH" and "MAX_TRAVERSE_SHOWN" to 16384.  I tried doubling that for the 30,000 measurement one but the software crashed when trying to open the Post Flux dialog with that setting.  Will need to do some more testing but here's how it looks for the attached file now:

![image](https://user-images.githubusercontent.com/25251719/60834987-e31c3400-a176-11e9-9dc3-5646e820f1ef.png)

**Comment by dnorgaard-usgs** [comment]
Max traverse increased for partial fix.  Created #138 for allowing unlimited traverse.
