### ISSUE TITLE
Deleting selected data is not working for this large evaluation log

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#133]
This issue may be related to the previous issue (unable to open evaluation logs with more than 4096 measurements). 

We opened the attached evaluationlog and clicked yes, open the first 4000 spectra. We then tried to delete selected data by using the vertical bars to select a part of the traverse and clicking the button on the bottom left. This caused unexpected results (the wrong data was removed).

[run13_20190703_2013evaluationLog_SO2_4000-8000.txt](https://github.com/NOVACProject/MobileDOAS/files/3366652/run13_20190703_2013evaluationLog_SO2_4000-8000.txt)

**Comment by dnorgaard-usgs** [comment]
It does appear related to #132.  I had issues on current version of MobileDOAS but seems to work after the change to address #132.  Will check in with you on these when you are back.
