### ISSUE TITLE
Add feature to allow real-time analysis of data collected by other software

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#137]
Increasingly, DOAS data is being collected using a variety of acquisition methods. For example, several groups are using small embedded computers to acquire data automatically inside an instrument (e.g. microDOAS uses a BeagleBone Black). Some groups are flying instruments on drones and collecting spectra with a variety of methods. The next step will be to telemeter these spectra (or parts thereof) back to the base station for real-time analysis. Finally, groups using spectrometers not currently supported by MobileDOAS may also want to use the MobileDOAS software for data analysis and real-time viewing.
This type of use could be facilitated by adding a feature to MobileDOAS where the user does not select a spectrometer for data acquisition, but instead selects a directory on the local computer. The software would then watch this directory for new spectra being written there (in the *.std format), and evaluate any new spectra as they appear.
Hopefully this would not require much of a change to the current operation of the software, just replacing the spectrometer acquisition object with a new file-reading object. The rest of the code should then be kept the same so there is really no difference in how the software works, only the data input is different. Also, instead of recording a dark current / offset spectrum, the user could be prompted to select a dark current / offset spectrum somewhere on the hard drive (with the last user's choice being remembered as the default).
I think this would really help people (me for sure!) use MobileDOAS in a very flexible way. Thanks for considering this option...

**Comment by dnorgaard-usgs** [comment]
Current changes for this in 6.3 branch of my fork.  Need to add still option to read offset if using adaptive mode.  Additional handling for this may also be necessary.

**Comment by dnorgaard-usgs** [comment]
- support for adaptive added
- need options to specify default sky/dark/offset files and use those if they don't exist in directory
- see if there is some way to get lat/lon/alt/time updated in eval log
- left axis label showing "Intensity" instead of "Column"

**Comment by christophkern** [comment]
Thanks for getting it this far! I've now finally been able to run some tests and have some suggestions for improvements:

1) In the Configuration -> Operation Setting menu:
Make 'Read from Directory' an alternate connection type in the 'Spectrometer' tab. The idea is that the program will read new files from the directory instead of from a USB or serial connection.

2) In the Control menu, remove 'View spectra from Directory'. The software should enter this mode when 'Start Traverse' is selected (or the green arrow) if "Read from Directory' is selected as the spectrometer connection in the configuration.

3) It would be very useful to support a bit more flexibility in the file name conventions. In the Configuration -> Operation Setting -> Directory tab, I suggest adding edit boxes for FilenamePrefix, NumberOfDigits, and FilenameSuffix. This would allow files like spec000001.std to be read, but also 00234_0.std (here, '_0.std' is the suffix).

4) Not sure how hard this would be, but including the possibility to search subdirectories for new files would be super useful. Any data recording software will generally create a new subdirectory for each new measurement. Adding a subdirectory search would allow the user to select the base directory in the Configuration - Operation Setting -> Directory tab, but not have to change that directory each time a new measurement is begun (which is typically several times per day). I'm not sure if searching all subdirs after each spectrum would delay things too much though. The solution might be a bit more complicated - e.g. take a survey of which subdirs exist in the beginning, keep checking all of them until new files begin appearing in one of them. At that point just look in that current subdir but keep checking if new subdirs have been added beyond what is known. In case a new subdir appears with new files, switch to that one and drop the other.

**Comment by dnorgaard-usgs** [comment]
Also, the directory mode will not use custom sky/dark/darkcur/offset files if there is already a file called sky_0.STD, dark_0.STD, etc in the directory.  Need to fix to make sure custom files are used if one is specified.

**Comment by dnorgaard-usgs** [comment]
Implemented 1 and 2 above.  Number 3 will not be implemented since it will require changes in many places to support re-evaluation.

Added more comments in Directory configuration dialog to clarify how the sky/dark/darkcur/offset files are read.

Added 'spectrometer dynamic range' field in Directory configuration dialog.

**Comment by dnorgaard-usgs** [comment]
Critical components required for this week's shipment to Alaska completed.  I will move #4 to a new ticket and create tickets for any other issues related to this.
