### ISSUE TITLE
Saving GPS speed, course, and data status in STD files

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#151]
Besides Latitude, Longitude and Altitude, the GPS also spits out Speed and Course information in the NMEA sentences. Speed is usually given in knots, but I suggest we convert it to m/s and then save it in a "Speed" parameter in the extended metadata of the STD files. Similarly, the "Course" should also be saved there. The Course is the direction the unit is travelling, with 0 being north, 180 being south etc. These parameters are extremely useful when trying to calculate wind speed and direction from airborne measurements, especially when using the 'wind circle' technique.
When making these changes, I also recommend we save the 'GPSDataStatus' which can be either A (=OK) or V (=Warning) and is included in most sentences.

**Comment by dnorgaard-usgs** [comment]
will go into next release (6.3)
