### ISSUE TITLE
Changes to metadata in *.std output files

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#154]
The new metadata being written to the std spectra files (Course, GPS Status, Speed) are great. However, we recently collected some std files that could not be read by DOASIS. The spectra were collected using the Control -> View Spectrometer Output option, and without connecting a GPS. In this case, the GPS Status was left blank in the output std files. The metadata entry was "GPS Status = ". This caused DOASIS to throw an error when trying to load the std file. I did also run Mobile DOAS with a GPS connected, and the STD files written then can be read by DOASIS.

I also recommend removing the unit ("m/s") from the Speed entry (e.g. "Speed = 4.3" rather than "Speed = 4.3 m/s". Though I understand the rationale for having a unit (there are various units used to indicate speed out there), a unit is not used in any of the other parameters (e.g. lat, lon, alt) and having one will make it harder to parse the speed into a floating point value by other software (e.g. DOASIS recognizes it as a string now).

I'm attaching an example std file that doesn't load in DOASIS. (remove the fake txt extension to test).

[Flame14685_CFLTest.std.txt](https://github.com/NOVACProject/MobileDOAS/files/6395165/Flame14685_CFLTest.std.txt)

**Comment by dnorgaard-usgs** [comment]
- Changed 'GPS Status' to 'GPSStatus' 
- Added 'NA' as a possible value for GPSStatus when GPS is not connected (vs "V" or "A" from gps when connected).  It is also the default value.
- Removed unit from Speed value
- GPSStatus will not get written if it is blank for any reason
