### ISSUE TITLE
Date incorrect in STD files

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#157]
Reported by Allan Lerner:
The original date stamp in MobileDOAS STD files is incorrect for measurements that have the same HH:MM:SS timestamp. The second spectrum with the duplicated timestamp is assigned to the previous day.

**Comment by christophkern** [comment]
I'm uploading a (partial) dataset recorded by helicopter at Okmok volcano this past summer. The Spectrometer was set to acquire data in 'Adaptive' mode, with a spectrum being saved every 1 second. In the lighting conditions encountered at Okmok led to exposure times in the 200 to 600 ms range. The adaptive mode averages as many spectrum as possible within the chosen integration time, so in this case, spectra were sometimes averaged, sometimes not. E.g., the measurement started off with spectra being recorded at 604 ms exp time. Here, no averaging was performed which meant that each individual measurement only took 604 ms plus some time for data transfer and analysis. Still, this was often complete in less than 1 second.

Since the GPS has a time resolution of 1 second, it happens that multiple spectra receive the same identical time stamp. In this example, spectra 2 and 3 were both recorded at 03:36:42, and 4 and 5 were both recorded at 03:36:43. This is perhaps not great, but an unavoidable result of the limited time resolution of the GPS.

What really throws things off, though, is that it appears that the second spectrum of such a pair receives an incorrect date stamp. If you look into the STD files themselves, you'll see that the date for spectrum 2 is 30.07.21, while the date for spectrum 3 is 29.07.21. 

The fix for this bug would be that both spectra receive the correct date stamp, regardless of whether or not they have the same acquisition time.

The Okmok example dataset is attached. I've only included the first 200 STD files to shrink the file size.

[Okmok_20210729_1937.zip](https://github.com/NOVACProject/MobileDOAS/files/7695259/Okmok_20210729_1937.zip)

**Comment by mattias42** [comment]
Resolved in the latest build of MobileDoas. Setting to closed now, but consider reopening if any remaining issues is found.
