### ISSUE TITLE
NumScans parameter set to 0 in spectra with long exposure times

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#160]
When collecting spectra in 'Adaptive' mode, the parameters ExpTime and NSpec are chosen such that NSpec * ExpTime is approximately equal (but does not exceed) the total integration time given in the Spectrometer configuration dialog ("Save a spectrum every: XX ms."). The maximum permitted ExpTime is equal to the total integration time and in this case NSpec should be equal to 1. However, recent tests at Kilauea have shown that when the ExpTime reaches the total integration time, NSpec was erroneously set to 0. This causes significant problems in the analysis, as the evaluation code does not know how many spectra were averaged, and thus the offset and dark current cannot be corrected (along with other problems). It's possible that this bug is being caused by a rounding issue, but the fix should be fairly simple: Just don't allow NSpec values of less than 1.

**Comment by christophkern** [comment]
Attaching an evaluation log from a sample dataset where this happens..

[Sum02_20210929_1640evaluationLog_SO2.txt](https://github.com/NOVACProject/MobileDOAS/files/7261701/Sum02_20210929_1640evaluationLog_SO2.txt)

**Comment by mattias42** [comment]
Resolved in the latest build of MobileDoas. Setting to closed now, but consider reopening if any remaining issues is found.
