### ISSUE TITLE
CSpectrumIO::WriteStdFile does not fill in all info

### ISSUE THREAD

**Issue by dnorgaard-usgs** [NOVACProject/MobileDOAS#71]
CSpectrumIO::WriteStdFile creates the .STD files.  At the bottom are a a bunch of configuration information that may or may not be used by the software.  Most of them do not appear to be used but may contain useful information.  For example, perhaps the FitHigh and FitLow should specify the fit window used.
	if(extendedFormat){
		fprintf(f, "Altitude = %.1lf\n", alt);
		fprintf(f, "Author = \"\"\n");
		fprintf(f, "Average = 0\n");
		fprintf(f, "AzimuthAngle = 0\n");
		fprintf(f, "Delta = 0\n");
		fprintf(f, "DeltaRel = 0\n");
		fprintf(f, "Deviation = 0\n");
		fprintf(f, "Device = \"\"\n");
		fprintf(f, "ElevationAngle = 90\n");
		fprintf(f, "ExposureTime = %ld\n",				integrationTime);
		fprintf(f, "FileName = %s\n", (LPCTSTR)fileName);
		fprintf(f, "FitHigh = 0\n");
		fprintf(f, "FitLow = 0\n");
		fprintf(f, "Gain = 0\n");
		fprintf(f, "Latitude = %.6lf\n",				lat);
		fprintf(f, "LightPath = 0\n");
		fprintf(f, "LightSource = \"\"\n");
		fprintf(f, "Longitude = %.6lf\n",				lon);
		fprintf(f, "Marker = %ld\n",							specLength / 2);
		fprintf(f, "MathHigh = %ld\n",						specLength - 1);
		fprintf(f, "MathLow = 0\n");
		fprintf(f, "Max = 0\n");
		fprintf(f, "MaxChannel = %ld\n",					specLength);
		fprintf(f, "Min = 0\n");
		fprintf(f, "MinChannel = 0\n");
		fprintf(f, "MultiChannelCounter = 0\n");
		fprintf(f, "Name = \"%s\"\n", (LPCTSTR)measName);
		fprintf(f, "NumScans = %ld\n",						exposureNum);
		fprintf(f, "OpticalDensity = 0\n");
		fprintf(f, "OpticalDensityCenter = %ld\n",	specLength / 2);
		fprintf(f, "OpticalDensityLeft = 0\n");
		fprintf(f, "OpticalDensityRight = %ld\n",	specLength - 1);
		fprintf(f, "Pressure = 0\n");
		fprintf(f, "Remark = \"\"\n");
		fprintf(f, "ScanGeometry = 0\n"); //(DoasCore.Math.ScanGeometry)SAZ: 137.41237083135 SZA: 31.5085943481828 LAZ: 298.523110145623 LAZ: 129.285101310559 Date: 1/5/2007 10:35:07 Lat.: 0 Lon.: 0\n");
		fprintf(f, "ScanMax = 0\n");
		fprintf(f, "Temperature = 0\n");
		fprintf(f, "Variance = 0\n");
	}

**Comment by mattias42** [comment]
This isn't too difficult and is probably best done by filling in the appropriate data in a CSpectrum structure and passing this to WriteStdFile. Needs to add a few more fields to the CSpectrum structure first...
