### ISSUE TITLE
Dual-channel spectrometer not implemented using USB

### ISSUE THREAD

**Issue by mattias42** [NOVACProject/MobileDOAS#8]
With the dual-channel spectrometer (S2000 series using ADC1000-USB) then it is not possible to collect data from the two channels simultaneously using the USB driver (Ocean Optics OmniDriver). The ability to do this isn't documented anywhere in the OmniDriver documentation.

**Comment by dnorgaard-usgs** [comment]
On Thu, Jan 4, 2018 at 11:07 AM, Norm Hoffer <norm.hoffer@oceanoptics.com> wrote:
Hi Diana:

Thank you for contacting Ocean Optics.

The only way that you can get synchronized acquisiton from the two channels of an SD2000 is to place them into external hardware trigger mode, and then send the 5V TTL trigger signal to both channels simultaneously to begin their acquisitions.

 http://oceanoptics.com/wp-content/uploads/External-Triggering-Options.pdf

http://oceanoptics.com/wp-content/uploads/S2000_Operating_Manual2.pdf

External Triggering is in Appendix F on pages 109-112.

 http://oceanoptics.com/wp-content/uploads/OEM-Data-Sheet-S2000.pdf

Sincerely,

Norm

 

Norm Hoffer
Technical Application Engineer, Ocean Optics, Inc.
Email: Norm.Hoffer@OceanOptics.com 
Tel: +1 727.733.2447

Ocean Optics Website

**Comment by dnorgaard-usgs** [comment]
There does not appear to be a way to get the measurements of both channels simultaneously from the spectrometer.  Still, it is desirable to support dual-beam measurements to see how well it would work if measurements are retrieved from the spectrometer serially.  It looks like MobileDOAS writes the measurements out for both channels when enabled, but does not do the evaluation.  Nor does the configuration tab allow for configuration of multiple channels.  (It does have a drop down for Master/Slave, but ultimately only one set of references are written the configuration file and only one is used do evaluation.)  This would need to be fixed.  Once the program is capable of doing the evaluation, the output would need to be written to the evaluation log.  Perhaps it is just a matter of writing additional columns for the Slave as it is for the Master.  The Wind and Plume dialogs will need to be analyzed to determine the format it is expecting.  These dialogs also don't appear to allow users to specify which portion of the measurements taken (e.g. start and end time) should be used for the calculations (it should not use all the measurements).  Christoph suggested adding a button or something to allow user to indicate when to start and stop taking measurements for wind/plume calculation.

**Comment by dnorgaard-usgs** [comment]
Some minor quirks in the evaluation configuration dialog were fixed (and also modified to allow insert/remove of multiple reference files at once). Other changes in CSpectrometer::ScanUSB and elsewhere were made to fix issue with second evaluation log not being written when 2 channels are enabled.  To configure, 2 fit windows are created (one for master and one for slave) and configured. The result is two evaluation logs being written and the UI looks something like this:

![image](https://user-images.githubusercontent.com/25251719/40503033-9485bc76-5f41-11e8-8f5d-04abf34c912e.png)

![image](https://user-images.githubusercontent.com/25251719/40503037-9952fff2-5f41-11e8-97b0-36256f90fe5c.png)

The Plume Height and Wind Measurement dialogs, however, seem to want both master and slave data written to the same evaluation log file.  Some changes are required to allow it to read both eval logs and process the data.

**Comment by dnorgaard-usgs** [comment]
Note, the changes does not support reading from both channels simultaneously as was originally desired. Data is read serially off of the spectrometer.

**Comment by dnorgaard-usgs** [comment]
New issue (#73) created for Plume Height and Wind Measurement dialog changes.
