### ISSUE TITLE
Temporary losing spectrometer connection during data collection and then regaining connection leads to huge negative readings at a constant value

### ISSUE THREAD

**Issue by dnorgaard-usgs** [NOVACProject/MobileDOAS#82]
Reported by Alan L:

Temporary losing spectrometer connection during data collection and then regaining connection leads to huge negative readings at a constant value (audible alert to an unchanging SO2 detection level would flag this as happening)

**Comment by mattias42** [comment]
Bug solved in commit 9df72ed where the program will attempt to reconnect if the connection with the spectrometer is lost. This fix does however seem to conflict with the design intentions of OceanOptics which causes some issues with exceptions in the driver. This fix does however keep the program running and will continuously attempt to reconnect with the spectrometer until successful.
