### ISSUE TITLE
Audio output is inconsistent

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#88]
The audio output is supposed to give a tone for each measured spectrum indicating the current overhead column density. It's a useful feature when the operator is not able to look at the screen. However, the current audio output is a bit confusing. I suggest changing to the following scheme:
1) Make audio output optional
2) If audio output is turned on, use a constant volume. This way, the user can set it to a desired level.
3) Instead of the volume, scale the pitch of the tone to the SO2 column density
4) Don't use a different type of tone for negative values. These are common and not really a problem.
5) Do use a different type of tone if an error occurs, for example if the GPS is lost or if the spectrometer fails or if the current spectrum is identical to the last one (indicating a problem with the spectrometer).
6) Not sure how practical, but it could be cool to have a voice indicate whenever pre-determined column amounts are exceeded or values drop below them. E.g. say '1,000' if the last column was less than 1,000 ppmm but the current one is larger than 1,000 ppmm or vice versa. There may have to be a minimum time between voice messages to avoid issues if values persist around one of the thresholds. Thresholds could either be set by the user or we could try the following: 200, 500, 1000, 2000, 5000, 8000, 10,000,  I know these are not evenly spaced, but let's try for numbers that are only 3 syllables when spoken.

**Comment by dnorgaard-usgs** [comment]
It appears not all audio devices support change in pitch: https://docs.microsoft.com/en-us/windows/desktop/multimedia/changing-pitch-and-playback-rate. My Windows 10 laptop does not support it.  For now, I will do a check to see if pitch change is supported.  If it is, I will set the pitch.  If it is not, I will set the volume.

Added option for audio on spectrometer configuration dialog:

![image](https://user-images.githubusercontent.com/25251719/42847872-550d859a-89d2-11e8-848b-c043a06b04dc.png)

Made modifications to use same sound for negative values as the positive ones.  Different sound is already in use for GPS error.

**Comment by dnorgaard-usgs** [comment]
The PlaySound function used in the code can play a sound specified by the given file name, resource, or system event.  Probably we would have to create wav files for each of those thresholds and install them on the user's PC somewhere for this to work.  Will keep thinking on it but at the moment it is not looking very practical.

https://msdn.microsoft.com/en-us/library/windows/desktop/dd743680(v=vs.85).aspx

**Comment by dnorgaard-usgs** [comment]
Also added audio support for second channel.  Previously only audio for first channel was played.
