### ISSUE TITLE
Spectrum acquisition rate could be better

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#98]
The spectrum acquisition rate could be better, especially when using 'adaptive' exposure time. In test measurements using a total integration time of 1000 ms, we have typically been recording one spectrum every 3 to 4 seconds. Even when using the 'fixed' exposure time, we typically record one spectrum every 2 to 3 seconds. Both of these experiments were performed with an SD2000 spectrometer connected via USB port.

I suspect that one reason for the relatively slow acquisition rate could be that a new spectrometer exposure time is set after each spectrum. Each time the exposure time is set, an entire readout of the spectrometer CCD will need to be thrown out, then a new spectrum will need to be acquired using the new exposure time, and this spectrum will then need to be transferred to the computer. The throwing out of one readout after each acquisition will slow down the effective acquisition rate by a factor of 2. This is not normally a huge issue, but it does e.g. prohibit us from currently using mobileDOAS for acquisition on airplanes because the platform is moving too quickly in between acquired spectra.

For the 'fixed' mode, re-setting the exposure time is not needed at all. We should just be grabbing every acquisition. Even for the 'adaptive' mode, I suggest that a range of acceptable saturation levels be implemented (e.g. 50% to 80 %). As long as the intensity of the current spectrum falls within this range, the exposure time should not be modified for the next scan. Instead, the software should just keep grabbing spectra until one is recorded that falls out of this range. Only then should a new exposure time be calculated (see separate GitHub issue related to this method) and sent to the spectrometer.

**Comment by dnorgaard-usgs** [comment]
Related to #99 

Probably need to pass in a flag to ScanUSB on whether integration time needs to be set.  Set flag to true only if integration time changes.

int CSpectrometer::ScanUSB(long sumInComputer, long sumInSpectrometer, double pResult[MAX_N_CHANNELS][MAX_SPECTRUM_LENGTH]) {

	// clear the old spectrum
	memset(pResult, 0, MAX_N_CHANNELS * MAX_SPECTRUM_LENGTH * sizeof(double));

	// Set the parameters for acquiring the spectrum
	for (int chn = 0; chn < m_NChannels; ++chn)
	{
		// Set the exposure time to use (this function takes exp-time in micro-seconds)
		m_wrapper.setIntegrationTime(m_spectrometerIndex, chn, m_integrationTime * 1000);

		// Set the number of co-adds
		m_wrapper.setScansToAverage(m_spectrometerIndex, chn, sumInSpectrometer);

	}

**Comment by dnorgaard-usgs** [comment]
Or do something like this:
```
                int integrationTime = m_wrapper.getIntegrationTime(m_spectrometerIndex);
		if (integrationTime != m_integrationTime * 1000) {
			m_wrapper.setIntegrationTime(m_spectrometerIndex, chn, m_integrationTime * 1000);
		}
```

**Comment by dnorgaard-usgs** [comment]
Would we want to do the same for setScansToAverage?

**Comment by dnorgaard-usgs** [comment]
Seems the above code change does not make any noticeable difference in acquisition rate.  The fixed exposure time mode is the only one that seems to produce STD files at a rate of one every 1-2 seconds (using ADC1000-USB).  I think there is more going on than what I commented in #99 on adaptive mode so will keep looking into that.  Automatic mode is also producing one STD file every 3-4 seconds so something is not right there too.

**Comment by dnorgaard-usgs** [comment]
Christoph reports that latest version has been running well.
