### ISSUE TITLE
Proposed change to method for determining adaptive exposure time

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#99]
I'm not entirely clear on how the exposure time of each spectrum is determined when using the 'adaptive' exposure time mode. It is possible that test measurements at different exposure times are made in between each acquired spectrum in order to determine the exposure time for the next spectrum. If this is true, it is at the cost of a slower acquisition rate. 

I'd like to suggest a different method: we should be calculating the exposure time (and NumScans) for the next acquired spectrum based on the current acquisition. If the current acquisition is too bright or too dark, i.e. its saturation is above or below the acceptable range indicated by the user, then a new exposure time should be determined. 

How to calculate the new exposure time? I suggest we simply modify the exposure time by a preset multiplication factor. In other words, we either increase or decrease the exposure time by X% as needed. Of course this preset factor X needs to be smaller than the width of the acceptable saturation range indicated by the user. Otherwise, the spectrum intensity may jump back and forth between too dark and too bright. Maybe we should just use the difference between minimum acceptable saturation and maximum acceptable saturation. For example, if the user has selected an acceptable range of 50% to 80% saturation, then we could use 80% - 50% = 30% as our modification factor. If a spectrum is recorded with less than 50% saturation, the exposure time would then be multiplied by 1.3 before the next spectrum is recorded. If a spectrum is recorded with more than 80% saturation, the exposure time would be multiplied by 0.7 before the next spectrum is recorded.

Currently, the exposure time of the next spectrum is determined by scaling up spectra in some sort of test, likely performed at very short exposure times. However, this causes some trouble when e.g. passing under a tree. If the telescope is blocked by some object during the exposure time test, then a very large exposure time is determined. The next spectrum is recorded at this extremely long exposure time. However, if the tree has now passed, then this next spectrum is completely over-saturated. Therefore, I think it's usually better to only change the exposure time incrementally. In the above example, the exposure time would only change by 30%. If the next spectrum where then a bit too bright, it would go back down by 30% without ever going to some astronomically high value.

**Comment by dnorgaard-usgs** [comment]
Below is what is called in the CMeasurement_Traverse::Run_Adaptive() when handling normal spectrum. While there's no user specified 'range' it does take the user specified 'percent' intensity.  If I understood below correctly, with default percent at 70, if saturation ratio is between 50 and 90 percent the integration time does not change. If saturation ratio is less than 50 then it is 1.2*integrationTime, if saturation ratio is greater than 90 it is integrationTime/1.2 (but always greater than min exposure time hard coded at 3.  This does sound somewhat similar to your approach, though the adjustment values and test intervals are slightly different.  If you have experienced the issues you mention though, maybe I missed something or below isn't working well and some numbers need tweaking.

short CSpectrometer::AdjustIntegrationTimeToLastIntensity(long maximumIntensity)
{
	const double ratioTolerance     = 0.2;
	const double minTolerableRatio  = std::max(0.0, m_percent - ratioTolerance);
	const double maxTolerableRatio  = std::min(1.0, m_percent + ratioTolerance);

	const double curSaturationRatio = maximumIntensity / (double)m_spectrometerDynRange;
	if (curSaturationRatio >= minTolerableRatio && curSaturationRatio <= maxTolerableRatio)
	{
		// nothing needs to be done...
		return m_integrationTime;
	}

	// Adjust the integration time
	long desiredIntegrationTime = (curSaturationRatio < minTolerableRatio) ? 
		(long)(m_integrationTime * (1.0 + ratioTolerance)) : 
		(long)(m_integrationTime / (1.0 + ratioTolerance));

	m_integrationTime = std::max((long)MIN_EXPOSURETIME, std::min(m_timeResolution, desiredIntegrationTime));

	return m_integrationTime;
}
